name: CI

on: [push, pull_request]

jobs:

  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  tests:
    name: Run tests with python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Test all
        run: make

      - name: Test coverage
        run: make coverage
