name: CI

on: [push, pull_request]

jobs:

  prepare:
    name: "Prepare for CI"
    runs-on: ubuntu-latest
    timeout-minutes: 1

    outputs:
      py_version: ${{ steps.versions.outputs.py_version }}

    steps:
      - uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          py_version="$(./get_version.sh __py_version__)"
          echo "::set-output name=py_version::$py_version"

  pre_commit:
    name: pre-commit checks
    needs: [ prepare ]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.prepare.outputs.py_version }}
      - uses: pre-commit/action@v3.0.0

  check_readme:
    name: "Check README help text"
    needs: [ prepare ]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.prepare.outputs.py_version }}

      - name: Install
        run: make install

      - name: Check if help text in README is up-to-date
        run: |
          # TODO: change branch name
          wget https://raw.githubusercontent.com/strboul/dotfiles/v0.4.4/bin/command-output-in-file
          chmod +x command-output-in-file
          ./command-output-in-file \
            --file "README.md" \
            --command "git-substatus --help" \
            --marker-start '<!-- help-output: start -->\n' \
            --marker-end '<!-- help-output: end -->\n'

  tests:
    name: "Run tests"
    needs: [ prepare ]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.prepare.outputs.py_version }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Test all
        run: make

      - name: Test coverage
        run: make coverage
